# Generated by Django 5.0.4 on 2024-10-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('job_title', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('part_time', 'جزئي'), ('full_time', 'دائم')], default='full_time', max_length=10)),
            ],
        ),
    ]
