# Generated by Django 5.0.4 on 2024-10-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('part_time', 'part_time'), ('full_time', 'full_time')], default='full_time', max_length=10),
        ),
    ]
