# Generated by Django 5.0.4 on 2024-10-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_app', 'Mobile Apps'), ('desktop_app', 'Desktop Apps'), ('ai_model', 'AI Model Programming'), ('data_analysis', 'Data Analysis'), ('scripts', 'Scripts'), ('web_scraping', 'Web Scraping and Data Collection'), ('subscription', 'Subscription System with Company')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
